name: djangoapp

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyjwt

  build-and-deploy:
    needs: setup
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy application
        run: |
          docker compose build
          docker compose up -d
