name: djangoapp

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  ci-checks:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./myapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyjwt

      - name: Run Django tests
        run: python manage.py test

  build-and-scan-image:
    needs: setup
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./myapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build application
        run: docker compose build

      - name: List images
        run: docker images

      - name: Scan my-app image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'django_testapp-web'
          output: trivy-report.txt
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - uses: actions/upload-artifact@v4
        name: Upload trivy report
        with:
          name: trivy-report
          path: ./trivy-report.txt
  deploy:
    needs: build-and-scan
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./myapp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy application
        run: docker compose up -d
