name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test-runner:
    runs-on: self-hosted  # This ensures it runs on your self-hosted runner
    steps:
      - name: Check Runner
        run: echo "GitHub Actions runner is working!"

      - name: Print System Info
        run: uname -a

      - name: List Directory Contents
        run: ls -la

